### ISSUE TITLE
Capitalize Enumerations (Values) and Remove Hypens

### ISSUE THREAD

**Issue by colinmacfarlane** [csg-org/esb-data-standard#14]
I recommend capitalizing all enumerations for each field, as it makes it easier to read and then an analyst can use these immediately in their visualizations. I would also say remove all the hyphens that are being used instead of spaces, which can be more difficult to type if you're trying to select a string. I also worry there could be issues with having to clean out em dashes, en dashes, and hyphens.

For example, **ApplicationRequestRejectionType** would be revised to:
- Duplicate
- Invalid
- Mismatch Voter Signature
- Missing Identification
- Missing SSN
- Missing State ID Number
- Missing Voter Signature
- Other

**Comment by JDziurlaj** [comment]
Hello @colinmacfarlane,
The ESB Data Standard follows conventions from other data formats in the elections space, such as VIP and the NIST series common data formats. The `tableschema` for ESB expects exact matches, such that em dashes, and en dashes will be caught and rejected, or normalized.

**Comment by jungshadow** [comment]
Thanks, @colinmacfarlane! John's response is right on. We've been operating under the style guides from other existing standards. VIP has the most explicit one [here](https://github.com/votinginfoproject/vip-specification/blob/vip52/STYLEGUIDE.md), which was adopted for the NIST 1500-100 standard. Since then, we've tried to model our work to fit into this universe. I hope this helps explain the rationale.
