### ISSUE TITLE
Replace JursidctionIdType and JurisdictionID with FIPS_Code and OCD_ID

### ISSUE THREAD

**Issue by vvuongfmg** [csg-org/esb-data-standard#19]
Currently, the standard collects three different types of jurisdiction IDs: OCD IDs, FIPS codes, and local IDs. However, it seems necessary to create separate variables for the IDs instead of having one overall ID variable, because jurisdictions will only provide one type of ID and limit information. For example, a jurisdiction might prefer to give its OCD ID despite having a FIPS Code as well. I recommend adding the following variables:

**Descriptive Name**: FIPS Code
**Variable Name**: FIPS_Code
**Data Type**: Numeric
**Required**: Yes
**Values**: 1-XXXXX - XX-XXXXX; -99: Missing; -101: Missing – Juris Field; -999: Error: Out of Range Value
**Description**: Specifies a single or double-digit numeric code for a given state, followed by a five digit numeric code for a given county within that state.

**Descriptive Name**: OCD ID
**Variable Name**: OCD_ID
**Data Type**: Alpha
**Required**: Yes
**Values**: -99: Missing; -101: Missing – Juris Field; -999: Error: Out of Range Value
**Description**: Specifies a jurisdiction in a commonly identifiable format ("ocd-jurisdiction/country:us/state:ex/place:example"), which allows for reuse with legislative datasets.

The above variables identify id type by virtue of their name and their values provide actual IDs, therefore eliminating the need for JurisdictionId and JursidctionIdtype as data fields. Local IDs were excluded because they were not present in the last dataset.

**Comment by jungshadow** [comment]
Hi @vvuongfmg! Thanks for this. There are a few reasons why I'm concerned about this request:

- Most of the identifiers you received in the dataset were generated in my processing from the data, otherwise all of the ids would be local.
- While local ids may not have been used in the last set of data, there are situations where it's not going to be easy to programmatically generate an OCD-ID or a FIPS from the existing dataset (NB: I'm happy that Wisconsin used FIPS to identify their municipalities).
- In addition, having two fields will largely guarantee that one column will be empty. From my review of many EMSs and VRDBs, they rarely, if ever, have a national identifier. Wisconsin is an outlier in this way.

I'm not necessarily against it, but this change would largely push more work onto us, the data processors, and I'm worried that we may accidentally create two identifiers that _may_ conflict.
