### ISSUE TITLE
Add new values to ApplicationRequestRejectionType

### ISSUE THREAD

**Issue by vvuongfmg** [csg-org/esb-data-standard#20]
To account for applications requests that were rejected due to not being received by a given deadline or mail application requests that were not postmarked by given deadlines, I recommend adding "Not Timely and "Postmark" values. Therefore, ApplicationRequestRejectionType would have the following values:

1: Duplicate
2: Invalid
3: Mismatch Voter Signature
4: Missing Identification
5: Missing SSN
6: Missing State ID Number
7: Missing Voter Signature
_8: Not Timely
9: Postmark_
10: Other
-99: Missing
-100: Valid Skip
-101: Missing - Juris Field
-999: Error: Out of Range Value

**Comment by jungshadow** [comment]
@vvuongfmg I don't remember seeing `other` comments regarding "application was not timely" or "postmark after deadline" as reasons for application rejections in the previous datasets. Do you happen to know how many states have deadline rejection policies? I think the application (FPCAs, at least) is usually applied forward rather than recorded as a rejection. In this case, I'm not sure we'd even see a transaction record for the requested election.
