### ISSUE TITLE
Write documentation on how all date fields adhere to ISO 8601

### ISSUE THREAD

**Issue by jungshadow** [csg-org/esb-data-standard#23]
## Issue
All date fields in the standard are supposed to adhere to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (e.g. 2018-01-01), however, that is never spelled out explicitly in the documentation. The only mention of ISO 8601 is in the breakdown of the file naming convention:

> `${ELECTION_DATE}` - The date of the election in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.

## Solution
Add section of the documentation that talks about the date fields in the preamble to the data field definitions.

**Comment by JDziurlaj** [comment]
I have a counter proposal (or maybe just an addition). Instead of mentioning `ISO 8601` in the preamble section, create a new section, called `Data Types`, which would list the data types used and the expected format for each. This would give us an opportunity to discuss the use of `array`, `boolean`, etc. If this section gets too long, I might suggest moving it to the bottom as an appendix.

**Comment by JDziurlaj** [comment]
See #28

**Comment by JDziurlaj** [comment]
Resolved via PR #28
